In [1]:
import pandas as pd
import numpy as np
import json, requests, time

import pycountry_convert as pc

In [2]:
mappings = pd.read_csv("cleaned_mappings.csv")
mappings.head()

,Faculty,Partner University,PU Module 1,PU Module 1 Title,PU Mod1 Credits,PU Module 2,PU Module 2 Title,PU Mod2 Credits,NUS Module 1,NUS Module 1 Title,NUS Mod1 Credits,NUS Module 2,NUS Module 2 Title,NUS Mod2 Credits,Pre Approved?
0,Faculty of Arts & Social Sci,The Hong Kong Polytechnic University,CBS241,Elementary Chinese II (for Non-Chinese speakin...,1.0,NaN,NaN,NaN,LAC2731,Department Exchange Module,3.0,NaN,NaN,NaN,Y
1,Faculty of Arts & Social Sci,The Hong Kong Polytechnic University,CC2C08,Mutual Impressions of China and the West,3.0,NaN,NaN,NaN,PS2238,Int'l Politics of NE Asia,4.0,NaN,NaN,NaN,Y
2,Faculty of Arts & Social Sci,Hong Kong University of Science & Technology,LANG1120,Chinese for Non-Chinese Language Background St...,1.0,NaN,NaN,NaN,LAC1731,Department exchange module,3.0,NaN,NaN,NaN,Y
3,Faculty of Arts & Social Sci,City University of Hong Kong,AIS3126,International Political Economy,3.0,NaN,NaN,NaN,PS3238,Int'l Political Economy,4.0,NaN,NaN,NaN,Y
4,Faculty of Arts & Social Sci,City University of Hong Kong,GE2210,China: A Socio-Political Transformation,3.0,NaN,NaN,NaN,PS2248,Chinese Politics,4.0,NaN,NaN,NaN,Y

This block of code has some work done manually since there is no easy way to check
which country each school is in

In [3]:
# df1 = pd.read_csv('school_country_continent_mapping.csv')

# countries = set(df1['Country'])
# full_continent_name = {
#     'AF': 'Africa',
#     'AS': 'Asia',
#     'EU': 'Europe',
#     'NA': 'North America',
#     'OC': 'Oceania',
#     'SA': 'South America'
# }

# for i in range(len(df1)):
#     if df1['Country'][i] != 'UNKNOWN':
#         c = pc.country_name_to_country_alpha2(df1['Country'][i], cn_name_format="default")
#         continent = pc.country_alpha2_to_continent_code(c)
#         df1['Continent'][i] = full_continent_name[continent]
#     else:
#         df1['Continent'][i] = 'Europe'

# df1.to_csv('')

In [4]:
with open('equivalentModuleMappings.json','r') as f:
    equivalent_module_mappings = json.load(f)

def get_equivalent_modules(modules, equivalent_module_mappings=equivalent_module_mappings):
    output = set()
    for module in modules:
        output.update(set(equivalent_module_mappings[module]))
    return output

### Note:
This list is created manually. I could not think of any fast/efficient way to determine if 2 schools
are the same entity

In [9]:
# modified_mappings = mappings.copy()

# equivalent_schools_mapping = {
#     'Aalto University': ['Aalto University, Helsinki'],
#     'Aarhus School of Business': ['Aarhus University'],
#     'Cornell University': ['Cornell Univ Coll of Agriculture & Life Sciences', 'Cornell Univ Coll of Human Ecology'],
#     'Georgetown University': ['Georgetown University Law Center','Georgetown University, Washington D.C.'],
#     'Humboldt University of Berlin': ['Humboldt-Universitaet zu Berlin'],
#     'Imperial College London': ['Imperial College Business School'],
#     'Leiden University': ['Leiden University Medical Center (LUMC)'],
#     'University College London': ['University College London, University of London'],
#     'Universite Catholique De Louvain': ['Universite Catholique de Louvain'],
# }

# for school in equivalent_schools_mapping:
#     for equiv in equivalent_schools_mapping[school]:
#         tmp_df = modified_mappings[modified_mappings['Partner University'] == equiv]
#         modified_mappings['Partner University'].iloc[tmp_df.index] = [school] * len(tmp_df)

# UCs_df = modified_mappings[modified_mappings['Partner University'] == 'University of California']
# for school in modified_mappings['Partner University'].unique():
#     if 'University of California' in school and school != 'University of California':
#         to_append = UCs_df.copy()
#         to_append['Partner University'] = [school] * len(to_append)
#         modified_mappings = modified_mappings.append(to_append)
# modified_mappings.index = range(len(modified_mappings))

# school_country_continent_mapping = pd.read_csv('school_country_continent_mapping.csv')
# country, continent = [], []
# for i in range(len(modified_mappings)):
#     school = modified_mappings['Partner University'][i]
#     df = school_country_continent_mapping[school_country_continent_mapping['Partner University'] == school]
#     try:
#         country.append(df['Country'].iloc[0])
#         continent.append(df['Continent'].iloc[0])
#     except:
#         print(school)
# modified_mappings['Country'] = country
# modified_mappings['Continent'] = continent

# modified_mappings.to_csv('cleaned_mappings_with_locations.csv',index=False)

In [11]:
modified_mappings = pd.read_csv('cleaned_mappings_with_locations.csv')

In [ ]:
def get_department(title):
    end_index = 0
    for i, char in enumerate(title):
        if not char.isalpha():
            end_index = i
            break
    return title[:end_index]
    
def department_filter(departments, mappings=modified_mappings):
    if len(departments) == 0:
        return mappings

    filter_function = lambda title : (type(title) == str) and (get_department(title) in departments)
    return mappings[mappings['NUS Module 1'].map(filter_function) | mappings['NUS Module 2'].map(filter_function)]


def module_filter(modules, mappings=modified_mappings):
    if len(modules) == 0:
        return mappings
    
    equivalent_modules = get_equivalent_modules(modules)
    filter_function = lambda title: (title is not np.nan) and ((title in equivalent_modules) or (title[:-1] in equivalent_modules))
    return mappings[mappings['NUS Module 1'].map(filter_function) | mappings['NUS Module 2'].map(filter_function)]

def school_filter(schools, mappings=modified_mappings):
    if len(schools) == 0:
        return mappings
    
    filter_function = lambda school: school in schools
    return mappings[mappings['Partner University'].map(filter_function)]

def essential_module_filter(modules, mappings=modified_mappings):
    schools = set(mappings['Partner University'])
    for module in modules:
        schools_with_mod = set(module_filter([module],mappings=mappings)['Partner University'])
        schools.intersection_update(schools_with_mod)
    output = module_filter(modules,school_filter(schools,mappings=mappings))
    output.sort_values('Partner University',inplace=True)
    return output

def optional_module_filter(modules, mappings=modified_mappings):
    schools = set()
    for module in modules:
        schools_with_mod = set(module_filter([module],mappings=mappings)['Partner University'])
        schools.update(schools_with_mod)
    output = module_filter(modules,school_filter(schools,mappings=mappings))
    output.sort_values('Partner University',inplace=True)
    return output

In [ ]:
def algorithm(essential_modules,optional_modules=[],schools=[],countries=[],continents=[],mappings=modified_mappings):
    """
    Returns a dictionary with key-value pairs being universities and the mappings of NUS modules to
    partner university modules. 
    
    output = {
        uni1: {NUS_mod1: [NUS_mod1_title, [[PU_mod1, PU_mod1_title], [PU_mod1, PU_mod1_title], ...]]},
    }
    """
    if continents != []:
        is_valids = [continent in continents for continent in mappings['Continent']]
        mappings = mappings[is_valids]
        
    if countries != []:
        is_valids = [country in countries for country in mappings['Country']]
        mappings = mappings[is_valids]
    
    
    if schools != []:
        restricted_by_school = school_filter(schools,mappings)
    else:
        restricted_by_school = mappings
    
    restricted_by_essential_modules = essential_module_filter(essential_modules, restricted_by_school)
    schools_with_essential_modules = restricted_by_essential_modules['Partner University'].unique()
    truth_series = [school in schools_with_essential_modules for school in mappings['Partner University']]
    valid_schools_with_optional_modules = mappings[truth_series]
    
    output_df = restricted_by_essential_modules
    if optional_modules != []:
        tmp_df = optional_module_filter(optional_modules, valid_schools_with_optional_modules)
        output_df = output_df.append(tmp_df)
    output_df.sort_values('Partner University',inplace=True)
    
    output_dict = {continent: {} for continent in output_df['Continent'].unique()}
    full_continent_name = {
        'AF': 'Africa',
        'AS': 'Asia',
        'EU': 'Europe',
        'NA': 'North America',
        'OC': 'Oceania',
        'SA': 'South America'
    }
    for i in range(len(output_df)):
        row = output_df.iloc[i]
        country_code = pc.country_name_to_country_alpha2(row['Country'], cn_name_format="default")
        continent = pc.country_alpha2_to_continent_code(country_code)

        continent_dict = output_dict[full_continent_name[continent]]
        if row['Country'] not in output_dict[full_continent_name[continent]]:
            continent_dict[row['Country']] = {}

        country_dict = continent_dict[row['Country']]
        if row['Partner University'] not in continent_dict[row['Country']]:
            country_dict[row['Partner University']] = {}

        if row['NUS Module 1'] is not np.nan:
            module_name = row['NUS Module 1']
            module_title = row['NUS Module 1 Title']
        else:
            module_name = row['NUS Module 2']
            module_title = row['NUS Module 2 Title']

        uni_dict = country_dict[row['Partner University']]
        if module_name not in uni_dict:
            uni_dict[module_name] = {'NUS Module Title': module_title, 'mappings': []}

        if row['PU Module 1'] is not np.nan:
            pu_module_name = row['PU Module 1']
            pu_module_title = row['PU Module 1 Title']
            uni_dict[module_name]['mappings'].append({'PU Module Code': pu_module_name, 'PU Module Title': pu_module_title})
        if row['PU Module 2'] is not np.nan:
            pu_module_name = row['PU Module 2']
            pu_module_title = row['PU Module 2 Title']
            uni_dict[module_name]['mappings'].append({'PU Module Code': pu_module_name, 'PU Module Title': pu_module_title})
    
    return output_dict

In [ ]:
def display_result(result):
    tab = '    '
    for continent in result:
        print(continent)
        for country in result[continent]:
            print(tab + country)
            for school in result[continent][country]:
                print(2*tab + school)
                for module in result[continent][country][school]:
                    print(3*tab+module)
                    print(4*tab+'NUS Module Title'+': ' + result[continent][country][school][module]['NUS Module Title'])
                    print(4*tab+'Mappings:')
                    for mapped in result[continent][country][school][module]['mappings']:
                        print(5*tab+f"{mapped['PU Module Code']}: {mapped['PU Module Title']}")

In [ ]:
essential_modules = ['CS2105','CS3230','CS2100']
optional_modules = ['ST2132','MA2108','MA3269']
result = algorithm(essential_modules, optional_modules,continents=['Asia','North America'])
display_result(result)

In [ ]:
result

In [ ]:
s = time.time()
import Algorithm
e = time.time()

In [ ]:
Algorithm.algorithm()